apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-staging

resources:
  - ../../base

configMapGenerator:
  - name: rag-shared-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - AUTHZ_ENABLED=true
      - CACHE_ENABLED=true
