"""服务间契约（Pydantic 模型）。所有跨服务请求/响应的唯一事实来源。"""

from packages.contracts.schemas import (
    ACL,
    ChatRequest,
    ChatResponse,
    Chunk,
    Citation,
    ContextItem,
    Document,
    EmbedRequest,
    EmbedResponse,
    GenerateRequest,
    GenerateResponse,
    HealthResponse,
    IndexRequest,
    IndexResponse,
    IngestRequest,
    IngestResponse,
    ModelInfo,
    RetrieveMode,
    RerankRequest,
    RerankResponse,
    SearchHit,
    SearchRequest,
    SearchResponse,
    Visibility,
)

__all__ = [
    "ACL",
    "ChatRequest",
    "ChatResponse",
    "Chunk",
    "Citation",
    "ContextItem",
    "Document",
    "EmbedRequest",
    "EmbedResponse",
    "GenerateRequest",
    "GenerateResponse",
    "HealthResponse",
    "IndexRequest",
    "IndexResponse",
    "IngestRequest",
    "IngestResponse",
    "ModelInfo",
    "RetrieveMode",
    "RerankRequest",
    "RerankResponse",
    "SearchHit",
    "SearchRequest",
    "SearchResponse",
    "Visibility",
]
